create table public.elevenlabs_crm_events (
    id bigint generated by default as identity primary key,
    event_id text not null,
    action text not null,
    response jsonb not null,
    created_at timestamp with time zone not null default now(),
    constraint elevenlabs_crm_events_event_id_key unique (event_id)
);

revoke all on table public.elevenlabs_crm_events from anon, authenticated, public;
grant all on table public.elevenlabs_crm_events to service_role;

create index if not exists idx_elevenlabs_crm_events_event_id
    on public.elevenlabs_crm_events (event_id);
